name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    image: node:14
    steps:
      - checkout
      - run: npm install
      - run: npm test